enable-magisk-update = true
parallel-jobs = 1
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "inotia00 ReVanced"
patches-version = "v4.16.1"
integrations-version = "v1.16.1"

#[YouTube]
#apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
#build-mode = "module"
#version = "19.44.37"
#included-patches = "'Force hide player buttons background' 'Hide Shorts dimming' 'MaterialYou'"
#excluded-patches = "'Alternative thumbnails' 'Bypass image region restrictions' 'Change player flyout menu toggles' 'Change start page' 'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Custom double tap length' 'Disable haptic feedback' 'Enable gradient loading screen' 'Hook YouTube Music actions' 'Hook download actions' 'Theme'"

#[Music]
#apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
#arch = "arm64-v8a"
#build-mode = "module"
#version = "7.16.53"
#included-patches = "'Hide overlay filter' 'Hide player overlay filter'"
#excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music' 'Enable landscape mode' 'Restore old style library shelf'"

[X]
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "piko ReVanced"
patches-version = "v1.46.1-dev.1"
integrations-version = "v1.35.0-dev.1"
version = "10.70.0-beta.1"
build-mode = "apk"
apkmirror-dpi = "480dpi"
arch = "arm64-v8a"
included-patches = "'Hide Banner' 'Hide Live Threads' 'Disable chirp font' 'Hide Community Notes' 'Hide FAB' 'Hide FAB Menu Buttons' 'Custom sharing domain' 'Customize profile tabs' 'Hide promote button' 'Force enable translate' 'Add ability to copy media link' 'Customize Navigation Bar items' 'Hide promote button' 'Force enable translate' 'Delete from database'"
